### your site title here

title: Jonathan Kizer
description: Sic Parvis Magna

baseurl: "" #name of GitHub repository
url: "https://jonathankkizer.github.io" #custom url to be used instead of GitHub repository
email: #


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 8
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
#facebook: "#"
#twitter: "#"
linkedin: "jonathan-kizer/"
github: "jonathankkizer"
#researchgate: "#"
#orcid: "#"

highlighter: rouge
markdown: kramdown

# Tracker
analytics: "UA-89273922-1"

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank

remote_theme: test
